package cn.com.employee.po;

import java.io.Serializable;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Range;

import cn.com.employee.validation.ValidGroup1;
import cn.com.employee.validation.ValidGroup2;
import cn.com.employee.validation.ValidGroup3;

public class Employeeinformation implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 5722606163648252572L;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employeeinformation.id
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employeeinformation.name
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	@Size(min = 1, max = 15, message = "{employee.name.length.message}", groups = { ValidGroup1.class })
	private String name;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employeeinformation.sex
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	private String sex;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employeeinformation.age
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	@NotNull(message = "{employee.age.isNull.message}", groups = { ValidGroup2.class })
	@Range(min = 18, max = 55, message = "{employee.age.range.message}", groups = { ValidGroup3.class })
	private Integer age;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employeeinformation.degree
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	private String degree;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employeeinformation.wages
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	private Double wages;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employeeinformation.address
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	private String address;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column employeeinformation.phone
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	private String phone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employeeinformation.id
	 *
	 * @return the value of employeeinformation.id
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employeeinformation.id
	 *
	 * @param id the value for employeeinformation.id
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employeeinformation.name
	 *
	 * @return the value of employeeinformation.name
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employeeinformation.name
	 *
	 * @param name the value for employeeinformation.name
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employeeinformation.sex
	 *
	 * @return the value of employeeinformation.sex
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employeeinformation.sex
	 *
	 * @param sex the value for employeeinformation.sex
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employeeinformation.age
	 *
	 * @return the value of employeeinformation.age
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employeeinformation.age
	 *
	 * @param age the value for employeeinformation.age
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employeeinformation.degree
	 *
	 * @return the value of employeeinformation.degree
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public String getDegree() {
		return degree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employeeinformation.degree
	 *
	 * @param degree the value for employeeinformation.degree
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public void setDegree(String degree) {
		this.degree = degree == null ? null : degree.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employeeinformation.wages
	 *
	 * @return the value of employeeinformation.wages
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public Double getWages() {
		return wages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employeeinformation.wages
	 *
	 * @param wages the value for employeeinformation.wages
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public void setWages(Double wages) {
		this.wages = wages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employeeinformation.address
	 *
	 * @return the value of employeeinformation.address
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employeeinformation.address
	 *
	 * @param address the value for employeeinformation.address
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column employeeinformation.phone
	 *
	 * @return the value of employeeinformation.phone
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column employeeinformation.phone
	 *
	 * @param phone the value for employeeinformation.phone
	 *
	 * @mbg.generated Wed Feb 06 14:35:18 CST 2019
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}
}